stages:
  - build
  - test
  - release

variables:
  DOCKER_HOST: tcp://docker:2375
  # This will instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  LATEST_TAG: $CI_REGISTRY_IMAGE:latest

image: docker:latest
services:
  - docker:dind

build:
  stage: build
  script:
    - chmod +x ci/build.sh
    - ci/build.sh

test-sanity:
  stage: test
  # need nvidia runtime, which cannot be done in dind
  image: $IMAGE_TAG
  tags:
    - gpu
  script:
    - salus-server --help

release:
  stage: release
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $LATEST_TAG
    - docker push $LATEST_TAG
  only:
    - master
