stages:
  - build
  - test
  - release

variables:
  DOCKER_HOST: tcp://docker:2375
  # This will instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  LATEST_TAG: $CI_REGISTRY_IMAGE:latest

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  tags:
    - gpu
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE_TAG || docker pull $LATEST_TAG || true
    - docker build --cache-from $IMAGE_TAG --cache-from $LATEST_TAG -t $IMAGE_TAG --build-arg APP_ENV=prod .
    - docker push $IMAGE_TAG

test-cuda-gpu:
  stage: test
  image: $IMAGE_TAG
  tags:
    - gpu
  script:
    - nvidia-smi

test-sanity:
  stage: test
  image: $IMAGE_TAG
  tags:
    - gpu
  script:
    - salus-server --help

release:
  stage: release
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $LATEST_TAG
    - docker push $LATEST_TAG
  only:
    - master
